-- =========================================================================
-- Ondal 초기 스키마 (P1 확정본)
-- 원본: docs 레포 docs/db/schema.md (2026-09-09 갱신본, BE main 56bc004 기준 엔티티 7개)
--
-- 규칙
--   - 이 파일은 수정 금지 - 스키마 변경은 V2, V3... 새 파일로만 (Flyway가 적용된 파일의 체크섬을 검증한다)
--   - 엔티티와 1:1 - Hibernate ddl-auto=validate 가 기동 시 대조한다 (테이블·열 존재, 타입, 널 여부)
--   - 제약 이름은 schema.md 의 이름 그대로 - 후속 마이그레이션이 이름으로 참조할 수 있게 고정
--   - FK 는 RESTRICT(기본) - 연쇄 삭제의 주체는 서비스 (zip 파일이 DB 밖에 있어 DB cascade 만으로는 파일이 남는다)
--   - PostgreSQL 은 FK 인덱스를 자동 생성하지 않음 - 조회 경로의 인덱스를 명시
--   - 시각 열은 timestamptz(6) = 자바 Instant(UTC), enum 은 varchar + CHECK (EnumType.STRING)
-- =========================================================================

create table users (
    id          bigint generated by default as identity primary key,
    login_id    varchar(50)  not null,   -- 홈페이지 계정과 매칭하는 키. 배정으로 선등록된 부원도 이 값으로 존재
    name        varchar(50)  not null,   -- 스텁 로그인에서는 login_id 와 동일, 홈페이지 연동 후 실제 이름
    global_role varchar(20)  not null,   -- ADMIN(임원단) | MEMBER(일반 부원)
    created_at  timestamp(6) with time zone not null,
    constraint uk_users_login_id unique (login_id),
    constraint chk_users_global_role check (global_role in ('ADMIN', 'MEMBER'))
);

create table cohorts (
    id          bigint generated by default as identity primary key,
    name        varchar(100) not null,
    description text,
    status      varchar(20)  not null,   -- ACTIVE(진행 중) | ARCHIVED(보관 - 열람만, 모든 변경 409)
    created_at  timestamp(6) with time zone not null,
    constraint chk_cohorts_status check (status in ('ACTIVE', 'ARCHIVED'))
);

create table enrollments (
    id         bigint generated by default as identity primary key,
    cohort_id  bigint      not null,
    user_id    bigint      not null,
    role       varchar(20) not null,     -- OPERATOR(교육운영진) | STUDENT(수강생). 승격만 있고 강등 없음
    created_at timestamp(6) with time zone not null,
    constraint uk_enrollment_cohort_user unique (cohort_id, user_id),
    constraint fk_enrollments_cohort foreign key (cohort_id) references cohorts (id),
    constraint fk_enrollments_user   foreign key (user_id)   references users (id),
    constraint chk_enrollments_role check (role in ('OPERATOR', 'STUDENT'))
);

create table assignments (
    id          bigint generated by default as identity primary key,
    cohort_id   bigint       not null,
    problem_no  integer      not null,   -- 문제 번호 - 전역 유일, 1000부터 (결정 9). 동시 채번 충돌은 uk 가 최후 방어 → 409
    session_no  integer,                 -- 차시(선택) - 중복·건너뜀 허용, 차시 밖 과제는 null
    title       varchar(200) not null,
    description text,
    due_at      timestamp(6) with time zone not null,   -- 마감(UTC) - 지각 판정은 저장하지 않고 submitted_at 과 비교
    created_at  timestamp(6) with time zone not null,
    constraint uk_assignments_problem_no unique (problem_no),
    constraint fk_assignments_cohort foreign key (cohort_id) references cohorts (id)
);
create index idx_assignments_cohort on assignments (cohort_id);

create table submissions (
    id             bigint generated by default as identity primary key,
    assignment_id  bigint       not null,
    user_id        bigint       not null,   -- enrollment 이 아니라 사용자 직접 참조 - 소속 해제 후에도 제출물은 남는다
    type           varchar(10)  not null,   -- CODE | FILE | LINK - 3종 택1 (결정 8)
    code_text      text,                    -- CODE 전용
    language       varchar(30),             -- CODE 전용·필수 (결정 7)
    file_name      varchar(255),            -- FILE 전용 - 업로드한 zip 원본 이름
    stored_path    varchar(500),            -- FILE 전용 - 저장 키 submissions/{UUID}.zip
    file_size      bigint,                  -- FILE 전용 - byte, 한도 10MB
    submitted_at   timestamp(6) with time zone not null,   -- 서버 수신 시각(UTC) - 마감 판정 기준
    score          integer,                 -- [P2 준비] 항상 null
    mentor_comment text,                    -- [P2 준비] 항상 null
    constraint fk_submissions_assignment foreign key (assignment_id) references assignments (id),
    constraint fk_submissions_user       foreign key (user_id)       references users (id),
    constraint chk_submissions_type check (type in ('CODE', 'FILE', 'LINK')),
    -- 3종 택1 정합성 (schema.md 4절) - 서비스 검증과 이중. 링크 개수(1~5)는 자식 테이블이라 여기서는 못 본다
    constraint chk_submissions_type_fields check (
           (type = 'CODE' and code_text is not null and language is not null
                          and file_name is null and stored_path is null and file_size is null)
        or (type = 'FILE' and stored_path is not null and file_name is not null and file_size is not null
                          and code_text is null and language is null)
        or (type = 'LINK' and code_text is null and language is null
                          and file_name is null and stored_path is null and file_size is null)
    )
);
create index idx_submissions_assignment_user on submissions (assignment_id, user_id, submitted_at);   -- "학생의 최신 제출" 조회
create index idx_submissions_user on submissions (user_id);

create table submission_links (
    id            bigint generated by default as identity primary key,
    submission_id bigint        not null,
    url           varchar(2048) not null,
    position      integer       not null,   -- 입력 순서 1~5 - 개수·연속성은 서비스 규칙
    constraint fk_submission_links_submission foreign key (submission_id) references submissions (id)
);
create index idx_submission_links_submission on submission_links (submission_id);

create table questions (
    id         bigint generated by default as identity primary key,
    cohort_id  bigint       not null,
    author_id  bigint       not null,     -- 작성자 - 등록 시 요청자로 고정. 소속 해제 후에도 글은 남는다
    title      varchar(200) not null,
    content    text         not null,     -- 최대 10000자는 서비스 검증
    created_at timestamp(6) with time zone not null,   -- 수정 시각 열 없음 (qna/design.md 결정 6)
    constraint fk_questions_cohort foreign key (cohort_id) references cohorts (id),
    constraint fk_questions_author foreign key (author_id) references users (id)
);
create index idx_questions_cohort_created on questions (cohort_id, created_at);   -- 분반 안 최신순 목록
create index idx_questions_author on questions (author_id);
